/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    int offset;
    int match_len;
    int literal;
} Token;
static inline __attribute__((unused)) Token Token_new(int offset, int match_len, int literal) {
    Token v;
    v.offset = offset;
    v.match_len = match_len;
    v.literal = literal;
    return v;
}

int min_match();
int match_len_at(Vec *, int, int, int);
Token best_match(Vec *, int, int);
Vec compress(Vec *, Arena *);
void copy_match(Vec *, int, int);
Vec decompress(Vec *, Arena *);

static inline Token *Token_box(Arena *dest, Token v) {
    Token *p = (Token *)arena_alloc(dest, sizeof(Token));
    *p = v;
    return p;
}

int min_match(void) {
    return 4;
}

int match_len_at(Vec * input __attribute__((unused)), int n __attribute__((unused)), int cand __attribute__((unused)), int pos __attribute__((unused))) {
    int __loop_result_0 __attribute__((unused));
    int len = 0;
    while (1) {
        if (((pos + len) >= n)) {
        __loop_result_0 = len;
        break;
        } else {
        if ((!(((*((int *)(vec_get(input, (cand + len))))) == (*((int *)(vec_get(input, (pos + len))))))))) {
        __loop_result_0 = len;
        break;
        } else {
        int __recur_tmp_0 = (len + 1);
        len = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_0;
}

Token best_match(Vec * input __attribute__((unused)), int n __attribute__((unused)), int pos __attribute__((unused))) {
    Token __loop_result_1 __attribute__((unused));
    int cand = 0;
    int best_len = 0;
    int best_off = 0;
    while (1) {
        if ((cand >= pos)) {
        if ((best_len >= min_match())) {
        __loop_result_1 = Token_new((pos - best_off), best_len, 0);
        break;
        } else {
        __loop_result_1 = Token_new(0, 0, (*((int *)(vec_get(input, pos)))));
        break;
        }
        } else {
        int len __attribute__((unused)) = match_len_at(input, n, cand, pos);
        if ((len > best_len)) {
        int __recur_tmp_0 = (cand + 1);
        int __recur_tmp_1 = len;
        int __recur_tmp_2 = cand;
        cand = __recur_tmp_0;
        best_len = __recur_tmp_1;
        best_off = __recur_tmp_2;
        continue;
        } else {
        int __recur_tmp_0 = (cand + 1);
        int __recur_tmp_1 = best_len;
        int __recur_tmp_2 = best_off;
        cand = __recur_tmp_0;
        best_len = __recur_tmp_1;
        best_off = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

Vec compress(Vec * input __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = vec_len(input);
    Vec tokens __attribute__((unused)) = vec_new(dest);
    void * __loop_result_2 __attribute__((unused));
    int pos = 0;
    while (1) {
        if ((pos < n)) {
        Token tok __attribute__((unused)) = best_match(input, n, pos);
        (void)(vec_push_(&(tokens), Token_box(dest, tok)));
        int __recur_tmp_0 = (pos + (((tok).match_len > 0) ? (tok).match_len : 1));
        pos = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return tokens;
}

void copy_match(Vec * out __attribute__((unused)), int offset __attribute__((unused)), int match_len __attribute__((unused))) {
    int start __attribute__((unused)) = (vec_len(out) - offset);
    void * __loop_result_3 __attribute__((unused));
    int k = 0;
    while (1) {
        if ((k < match_len)) {
    (void)(vec_push_(out, vec_box_i32(out, (*((int *)(vec_get(out, (start + k))))))));
        int __recur_tmp_0 = (k + 1);
        k = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
}

Vec decompress(Vec * tokens __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = vec_len(tokens);
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_4 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i < n)) {
    Token tok __attribute__((unused)) = (*((Token *)(vec_get(tokens, i))));
    if (((tok).match_len > 0)) {
    (void)(copy_match(&(out), (tok).offset, (tok).match_len));
    } else {
    (void)(vec_push_(&(out), vec_box_i32(&(out), (tok).literal)));
    }
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return out;
}

